### ISSUE TITLE
Bug in _disconnect functions on QObjects

### ISSUE THREAD

**Issue by tlambert03** [pyapp-kit/app-model#157]
some more details ... ultimately, I think this bug is due to a failure in the disconnection strategy i mentioned above in https://github.com/pyapp-kit/app-model/issues/147#issuecomment-1801076340.

If you add `self.sample_menu.destroyed.connect(lambda: print("DESTROY"))` somewhere, you'll see that the `destroyed`
event IS indeed emitted, but the intended `_disconnect` callback is never getting called (and so `self._app.menus.menus_changed.disconnect(self._on_registry_changed)` is never getting called either).  I think this probably means that the strategy of having a QObject connect its own method to its `destroyed` signal isn't going to work (presumably that callback method *itself* is cleaned up and no longer called).

If you try to outsmart it by using a locally defined function closing on the QObject:

```python
        @self.destroyed.connect
        def _disconnect() -> None:
            self._app.menus.menus_changed.disconnect(self._on_registry_changed)
```

then the _disconnect function *does* get called, but then psygnal has an issue actually executing the disconnection cause it can no longer find the callback to disconnect it:

```pytb
Traceback (most recent call last):
  File "/Users/talley/dev/self/app-model/src/app_model/backends/qt/_qmenu.py", line 58, in _disconnect
    self._app.menus.menus_changed.disconnect(self._on_registry_changed)
  File "src/psygnal/_signal.py", line 827, in disconnect
  File "src/psygnal/_signal.py", line 799, in _slot_index
  File "src/psygnal/_weak_callback.py", line 130, in weak_callback
  File "src/psygnal/_weak_callback.py", line 363, in __init__
  File "src/psygnal/_weak_callback.py", line 190, in __init__
  File "src/psygnal/_weak_callback.py", line 258, in object_key
RuntimeError: wrapped C/C++ object of type QModelSubmenu has been deleted
```

It's possible we could catch and special case that in psygnal itself (to handle the case where essentially all attribute access is no longer permitted on the previously connected callback)... but I need to look into that.

----- 
and one final detail, while I'm looking into this, I think it would also be very reasonable for npe2's PluginContext to catch errors in the dispose method:

```python
class PluginContext:
    def _dispose(self):
        while self._disposables:
            try:
                self._disposables.pop()()
            except Exception as e:
                logger.warn(f'Error while disposing blah blah {e}')
```

_Originally posted by @tlambert03 in https://github.com/pyapp-kit/app-model/issues/147#issuecomment-1803898923_

**Comment by tlambert03** [comment]
oh! It looks like that issue in disconnection is already fixed by https://github.com/pyapp-kit/psygnal/pull/236 (which hasn't been released yet)

**Comment by lucyleeow** [comment]
> that issue in disconnection is already fixed

you mean "the intended _disconnect callback is never getting called" problem?

**Comment by tlambert03** [comment]
I'm still working on it, will close soon!
